### ISSUE TITLE
May i help with this

### ISSUE THREAD

**Issue by irhrhd** [DigitalTeal/website#1]
May i help be a coder?

**Comment by ChickenOnYT** [comment]
are you 14 or older

**Comment by irhrhd** [comment]
Exactly 14

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
i could actually use help but can you do php, html, css, and js

**Comment by irhrhd** [comment]
And I have discord so you can contact me

**Comment by irhrhd** [comment]
Yes I can do those I don’t know python though so don’t ask me that lol

**Comment by ChickenOnYT** [comment]
whats your discord i'll contact you later im in school

**Comment by irhrhd** [comment]
ThePoPo_Is_Here#8875

**Comment by ChickenOnYT** [comment]
sent a friend request
